-- select * from items order by price 
-- select * from items where price >79 order by price desc
-- select first_name, lest_name from customers where id < 4 order by first_name
-- select lest_name from customers order by lest_name desc